# Generated by Django 5.2.1 on 2025-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodel', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='screenshot',
            field=models.FileField(upload_to=''),
        ),
    ]
