# Generated by Django 5.2.1 on 2025-05-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodel', '0003_alter_screenshots_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='DB_files'),
        ),
        migrations.CreateModel(
            name='Processed_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_video', models.FileField(upload_to='DB_files')),
                ('list_nums_persons', models.JSONField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aimodel.video')),
            ],
        ),
        migrations.DeleteModel(
            name='Screenshots',
        ),
    ]
